project:
  type: website

website:
  title: " "
  navbar:
    background: success
    search: true
    left:
      - text: "Inicio"
        file: index.qmd
      - text: "Nuestro projecto"
        menu:
          - about.qmd
          - canva.qmd
          - licencia.qmd
      - text: "Equipo"
        file: equipo.qmd
      - text: "Cómo contribuir"
        menu:
          - contribuciones.qmd
          - conducta.qmd
          - text: "Formulario" 
            href: https://forms.gle/Ho6UufEDyvT3ukh6A
    tools:
      - icon: email
        href: https://twitter.com
      - icon: github
        href: https://github.com/PatriLoto/sitio_ciencia_abierta_en_latinoamerica

format:
  html:
    theme: lux
    css: styles.css
    toc: true
    lang: es

editor: visual

