project:
  type: website

website:
  title: " "
  navbar:
    background: success
    search: true
    left:
      - text: "Inicio"
        file: index.qmd
      - text: "Conoce nuestro projecto"
        file: about.qmd
      - text: "Equipo"
        file: equipo.qmd
      - text: "Contribuciones"
        file: contribuciones.qmd
    tools:
      - icon: mail
        href: https://twitter.com
      - icon: github
        href: https://github.com/PatriLoto/sitio_ciencia_abierta_en_latinoamerica

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

