---
title: "Open canvas"
---

Si te interesa conocer más sobre el proyecto, te sugerimos que leas el siguiente detalle sobre el producto que proponemos y la comunidad que deseamos armar alrededor del proyecto.

### Acerca Del Producto

Los problemas detectados son:

1.  La escasa disponibilidad de recursos como talleres, cursos, eventos, y espacios sobre cómo iniciarse en ciencia abierta en la región de Latinomérica.

2.  La inexistencia de una plataforma o repositorio que contenga y centralice información actualizada sobre materiales de ciencia abierta en español.

3.  La dificultad en cuanto a encontrar comunidades y redes que adopten y empleen principios abiertos en nuestra región.

##### **Solución Propuesta**

Repositorio colaborativo que reúna información actualizada y accesible de recursos, eventos, y comunidades de ciencia abierta en español de América Latina.

##### **Métricas principales**

-   Cantidad de eventos, comunidades y recursos disponibles en el repositorio (x mes, x año).

-   Google analytics - cantidad de visitas que tiene el sitio del proyecto(medida de visibilidad)

-   Cantidad de colaboradores y/o contribuciones al proyecto.

-   Cantidad de eventos, comunidades y recursos agregados (x mes, x año).

### Acerca de la Comunidad

##### **Propuesta de valor única**

Primer repositorio colaborativo sobre ciencia abierta en Latinoamérica, de fácil uso y con contenido completamente en español.

##### **Perfiles de los usuarios**

Investigadores, estudiantes y comunidades con interés en ciencia abierta en América Latina que utilicen el repositorio con el fin de entrar en contacto con otros actores regionales y locales de prácticas abiertas y/o estar al tanto de eventos relacionados con ciencia abierta.

Canales de comunicación con los usuarios

-   Sitio web del proyecto.
-   Red social (twitter) que permitirá darle difusión al proyecto.
-   Newsletter.
-   Google forms para el envío de contribuciones.

##### **Perfiles de los colaboradores**

Científicos, investigadores y organizaciones que quieran difundir su trabajo aportando material para sumarlo al repositorio.\
Científicos, investigadores y técnicos que colaboren con el mantenimiento y/o mejora del repositorio y/o documentación del mismo.

Canales de comunicación con los colaboradores

-   Plataforma donde estará alojado el repositorio/proyecto (github).
-   Red social que permite dar difusión al llamado a colaboradores al proyecto.
-   Plataforma abierta para la comunicación entre colaboradores que permita crear comunidad.
-   Google forms.
